theme: minima

title: "Emanuel Mota"
description: "Electrical Engineering | Power Electronics | Embedded Systems"

author: "Emanuel Mota"

github_username: Emamnuel

markdown: kramdown

minima:
  social_links:
    github: Emamnuel
